plugins {
    id 'com.android.application'
}

android {
    namespace "com.xenione.demos.digit"
    compileSdk 36

    defaultConfig {
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.13.2'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.github.QuadFlask:colorpicker:0.0.15'
    implementation project(':digit')
}
